name: WordPress Security Scan

on:
  push:
    branches: [ main ]  # هر بار روی برنچ اصلی پوش کنید، اسکن اجرا می‌شود

jobs:
  wordpress-wpscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        run: |
          cd docker
          docker-compose up -d

      - name: Wait for WordPress to be ready
        run: |
          echo "Waiting for WordPress to start..."
          sleep 30  # زمان کافی برای بالا آمدن کامل پایگاه‌داده و وردپرس

      - name: Run WPScan
        run: |
          docker run --rm wpscanteam/wpscan --url http://localhost:8080 --enumerate u,vp,vt --force --api-token ${{ secrets.WPSCAN_API_TOKEN }}
